site_name: ASEAN DIWA Portal
site_description: Data Insights for Women in ASEAN
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Data Explorer: explorer.md
  - Country Profiles: country-profiles.md
  - Comparison: comparison.md
  - Sources: sources.md
